// Writes assets/boards/versions.js: a short content hash for every board image and video.
// The site appends it to each URL (?v=…), so browsers and GitHub Pages' cache fetch new
// artwork as soon as it changes instead of showing the old file for up to 10 minutes.
// Runs automatically after `npm run render` and `npm run record`; `npm run stamp` by hand.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { ROOT, OUT } from './lib.mjs';

export async function stamp() {
  const versions = {};
  for (const option of (await fs.readdir(OUT)).sort()) {
    const dir = path.join(OUT, option);
    if (!(await fs.stat(dir)).isDirectory()) continue;
    for (const f of (await fs.readdir(dir)).sort()) {
      if (!/\.(png|jpg|mp4)$/.test(f)) continue;
      const hash = crypto.createHash('sha1').update(await fs.readFile(path.join(dir, f))).digest('hex').slice(0, 10);
      versions[`${option}/${f}`] = hash;
    }
  }
  const file = path.join(OUT, 'versions.js');
  await fs.writeFile(file, `// Generated by tools/stamp.mjs. Do not edit.\nwindow.BOARD_VERSIONS = ${JSON.stringify(versions, null, 2)};\n`);
  console.log('✓', path.relative(ROOT, file), `(${Object.keys(versions).length} files)`);
}

if (import.meta.url === `file://${process.argv[1]}`) await stamp();
